name: Testcafe Test

on:
  schedule:
  - cron:  '0 10 * * *'
  
  
jobs:
 test:
   name: Scheduleed Test
   runs-on: ubuntu-latest
   steps:
   - name: Checkout code
     uses: actions/checkout@v2
 
   - name: Use Node.js
     uses: actions/setup-node@v1
     with:
       node-version: '12.x'
   - name: Run tests
     run: |-
       echo "Install UI tests node_modules";
       npm ci
       npm run test:ci
